apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: infra
spec:
  
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.0
          ports:
            - containerPort: 80
          resources:
             requests:
               memory: "64Mi"
               cpu: "100m"

