apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: infra
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.20.0
          ports:
            - containerPort: 80

